models/restaurants.py
from models import db
from models.users import User

class Restaurant(db.Model):

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(250), nullable=False)
    menu_items = db.relationship("MenuItem", backref="restaurant")
    user_id = db.Column(db.Integer, db.ForeignKey(User.id))

    def serialize_menu_items(self):
        return {
            "restaurant_id": self.id,
            "name": self.name,
            "menu_items": [i.name for i in self.menu_items]
        }

    @property
    def serialize(self):
        return {
            "restaurant_id": self.id,
            "name": self.name
        }

    def __init__(self, name, user_id):
        self.name = name
        self.user_id = user_id

    def __repr__(self):
        return '<Restaurant:{}>'.format(self.name)

controllers/menu_item_cont.py
from flask import Blueprint, flash, render_template, url_for, request, redirect
from models.menu_items import MenuItem, Restaurant, db
from flask import session as login_session

# create a blueprint for all menu items
menu_items = Blueprint("menu_item", __name__)


# route to create a menu item for a given restaurant
# we only allow creation of an item if a user is currently logged in
# if this route gets a post request, we'll store the submitted form data in the DB
@menu_items.route("/restaurant/<int:restaurant_id>/menu/new", methods=['GET', 'POST'])
def create(restaurant_id):
    user_id = login_session.get('id')
    restaurant = Restaurant.query.get(restaurant_id)
    if user_id:
        if request.method == 'POST':
            restaurant = Restaurant.query.get(restaurant_id)
            name = request.form.get("name")
            desc = request.form.get("desc")
            price = request.form.get("price")
            menu_item = MenuItem(name=name, desc=desc, price=price, restaurant_id=restaurant.id)
            db.session.add(menu_item)
            db.session.commit()
            flash("Menu item added successfully!")
            return redirect(url_for("restaurant.show_menu", restaurant_id=restaurant.id))
        else:
            return render_template("menu/form.html", menu_item='', restaurant=restaurant)
    else:
        flash('Operation not allowed. Please log in to create a menu item')
        return redirect(url_for('restaurant.index'))


# updates a menu item for a given restaurant
# only performs the update when a POST is received on this route
# if we have a get request, then we'll render the same form as used for the create route
# we only perform an operation if the menu_item exists. This prevents users trying random urls
# as the id's are in plain views
@menu_items.route("/restaurant/<int:restaurant_id>/menu/<int:menu_item_id>/edit", methods=['GET', 'POST'])
def update(restaurant_id, menu_item_id):
    restaurant = Restaurant.query.get(restaurant_id)
    menu_item = MenuItem.query.get(menu_item_id)
    user_id = login_session.get('id')
    if user_id:
        if menu_item:
            if request.method == 'GET':
                return render_template("menu/form.html", menu_item=menu_item, restaurant=restaurant)
            elif request.method == 'POST':
                menu_item.name = request.form.get("name")
                menu_item.desc = request.form.get("desc")
                menu_item.price = request.form.get("price")
                db.session.add(menu_item)
                db.session.commit()
                flash("Menu item updated successfully!")
                return redirect(url_for("restaurant.show_menu", restaurant_id=menu_item.restaurant.id))
            else:
                flash("Invalid Action, Please try again")
                return redirect(url_for("restaurant.menu", restaurant_id=menu_item.restaurant.id))
        else:
            flash("Item not found, please try again")
            return redirect(url_for("restaurant.index"))
    else:
        flash('Operation not allowed. Please log in to create a menu item')
        return redirect(url_for('restaurant.index'))


# remove a menu item for a given restaurant
# we only remove an item if a user if currently logged in
# We also only remove an item if it exists, otherwise we tell the user to try again
# this prevents users messing with the url and trying random requests.
@menu_items.route("/restaurant/<int:restaurant_id>/menu/<int:menu_item_id>/delete", methods=['GET', 'POST'])
def delete(restaurant_id, menu_item_id):
    restaurant = Restaurant.query.get(restaurant_id)
    menu_item = MenuItem.query.get(menu_item_id)
    user_id = login_session.get('id')
    if user_id:
        if menu_item:
            if request.method == "GET":
                return render_template("menu/delete.html", menu_item=menu_item)
            elif request.method == "POST":
                db.session.delete(menu_item)
                db.session.commit()
                flash("Menu item successfully deleted!")
                return redirect(url_for("restaurant.show_menu", restaurant_id=restaurant.id))
            else:
                flash("Invalid operation. Please try again")
                return redirect(url_for("restaurant.show_menu", restaurant_id=restaurant.id))
        else:
            flash("Menu item not found. Please try again")
            return redirect(url_for("restaurant.show_menu", restaurant_id=restaurant.id))
    else:
        flash('Operation not allowed. Please log in to create a menu item')
        return redirect(url_for('restaurant.index'))

controllers/restaurant_cont.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from models.restaurants import Restaurant, db
from flask import session as login_session

# make a restaurant blueprint
restaurant = Blueprint('restaurant', __name__)


# index to display all restaurants
# only dispaly the CRUD version of the webpage if users are logged in
# otherwise we serve a read only version of the page
@restaurant.route('/restaurants/')
def index():
    restaurants = Restaurant.query.all()
    user_id = login_session.get('id')
    if user_id:
        return render_template("restaurant/index.html", restaurants=restaurants)
    else:
        return render_template("restaurant/logged_out_index.html", restaurants=restaurants)


# creates a new restaurant and serves the form to do so
# upon successful creation redirect to index, otherwise
# flash the error and re-render the form template
@restaurant.route("/restaurant/new/", methods=['GET', 'POST'])
def create():
    user_id = login_session.get('id')
    if user_id:
        if request.method == 'GET':
            return render_template("restaurant/form.html", restaurant='')
        elif request.method == 'POST':
            rest_name = request.form.get("restaurant_name")
            if rest_name:
                new_restaurant = Restaurant(name=rest_name, user_id=login_session.get('id'))
                db.session.add(new_restaurant)
                db.session.commit()
                return redirect(url_for("restaurant.index"))
            else:
                flash("Please enter a valid restaurant name")
                return render_template("restaurant/form.html", restaurant='')
        else:
            flash("Invalid Submission, please try again")
            return render_template("restaurant/form.html", restaurant='')
    else:
        flash("operation not allowed. Please log in to create a restaurant")
        return redirect(url_for('restaurant.index'))


# Updates the name of an existing restaurant
# if the restaurant cannot be found, we'll flash an error and re-render the form
@restaurant.route("/restaurant/<int:restaurant_id>/edit/", methods=['GET', 'POST'])
def update(restaurant_id):
    user_id = login_session.get('id')
    current_restaurant = Restaurant.query.get(restaurant_id)
    if user_id:
        if current_restaurant:
            if request.method == "GET":
                return render_template("restaurant/form.html", restaurant=current_restaurant)
            elif request.method == "POST":
                name = request.form.get("restaurant_name")
                if name:
                    current_restaurant.name = name
                    db.session.add(current_restaurant)
                    db.session.commit()
                    flash("Restaurant has been updated to {}".format(current_restaurant.name))
                    return redirect(url_for('restaurant.index'))
            else:
                flash("Invalid Request, please try again")
                return render_template("restaurant/form.html", restaurant='')
        else:
            flash("The restaurant could not be found. Please try again")
            return render_template("restaurant/form.html", restaurant='')
    else:
        flash("operation not allowed. Please log in to update a restaurant")
        return redirect(url_for('restaurant.index'))


# route to delete a restaurant
# only allow the delete if a user is logged in
@restaurant.route("/restaurant/<int:restaurant_id>/delete/", methods=['GET', 'POST'])
def delete(restaurant_id):
    current_restaurant = Restaurant.query.get(restaurant_id)
    user_id = login_session.get('id')
    if user_id:
        if current_restaurant:
            if request.method == "GET":
                return render_template("restaurant/delete.html", restaurant=current_restaurant)
            elif request.method == 'POST':
                db.session.delete(current_restaurant)
                db.session.commit()
                flash("Restaurant Deleted Successfully!")
                return redirect(url_for("restaurant.index"))
            else:
                flash("Invalid Request, please try again")
                return render_template("restaurant/delete.html", restaurant='')
        else:
            flash("Restaurant not found, please try again")
            return render_template("restaurant/delete.html", restaurant='')
    else:
        flash("operation not allowed please log in to delete a restaurant item")
        return redirect(url_for('restaurant.index'))


@restaurant.route("/restaurant/<int:restaurant_id>/menu")
def show_menu(restaurant_id):
    current_restaurant = Restaurant.query.get(restaurant_id)
    user_id = login_session.get('id')
    if current_restaurant:
        if user_id:
            return render_template("restaurant/menu.html", restaurant=current_restaurant)
        else:
            return render_template("restaurant/logged_out_menu.html", restaurant=current_restaurant)
    else:
        flash("Restaurant not found. Please try again")
        return render_template("restaurant/index.html", restaurant='')

templates/restaurant/delete.html
{% extends "layout.html" %}

{% block nav %}
    {% include 'heading.html' %}
{% endblock %}

{% block content %}
    <h4>Are you sure you want to delete {{ restaurant.name }}?</h4>
    <form method="post">
        <button type="submit" class="btn btn-danger">Confirm</button>
        <a class="btn btn-success" href={{ url_for("restaurant.index", restaurant_id=restaurant.id) }}>Cancel</a>
    </form>
{% endblock %}

templates/restaurant/form.html
{% extends "layout.html" %}

{% block nav %}
    {% include 'heading.html' %}
{% endblock %}

{% block content %}

    <form method="post">
        <div class="form-group">
            <label for="restaurant-name">Restaurant Name</label>
            <input type="text" name="restaurant_name" id="restaurant-name" class="form-control" value="{{ restaurant.name }}">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
            <a class="btn btn-success" href={{ url_for("restaurant.index", restaurant_id=restaurant.id) }}>Cancel</a>
        </div>
    </form>

{% endblock %}

templates/restaurant/index.html
{% extends "layout.html" %}


{% block nav %}
    {% include 'heading.html' %}
{% endblock %}

{% block content %}
    {% for restaurant in restaurants %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>{{ restaurant.name }}</h3>
            </div>
            <div class="panel-body">
                <a class="btn btn-primary" href={{ url_for("restaurant.show_menu", restaurant_id=restaurant.id) }}>Menu</a>
                <a class="btn btn-success" href={{ url_for("restaurant.update", restaurant_id=restaurant.id) }}>Edit</a>
                <a class="btn btn-danger" href={{ url_for("restaurant.delete", restaurant_id=restaurant.id) }}>Delete</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/restaurant/logged_out_index.html
{% extends "layout.html" %}

{% block nav %}
    {% include 'restricted_heading.html' %}
{% endblock %}

{% block content %}
    {% for restaurant in restaurants %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>{{ restaurant.name }}</h3>
            </div>
            <div class="panel-body">
                <a class="btn btn-primary" href={{ url_for("restaurant.show_menu", restaurant_id=restaurant.id) }}>Menu</a>
            </div>
        </div>
    {% endfor %}
{% endblock %}

templates/restaurant/logged_out_menu.html
{% extends "layout.html" %}

{% block nav %}
    {% include 'restricted_heading.html' %}
{% endblock %}

{% block content %}
    <h1>{{ restaurant.name }} Menu</h1>
    {% for item in restaurant.menu_items %}
        <h4>{{ item.name }}</h4>
        <div>{{ item.desc }}</div>
        <div>{{ item.price }}</div>
    {% endfor %}
{% endblock %}

templates/restaurant/menu.html
{% extends "layout.html" %}

{% block nav %}
    {% include 'heading.html' %}
{% endblock %}

{% block content %}
    <a class="btn btn-success" href={{ url_for("menu_item.create", restaurant_id=restaurant.id) }}>Add Menu Item</a>
    <h1>{{ restaurant.name }} Menu</h1>
    {% for item in restaurant.menu_items %}
        <h4>{{ item.name }}</h4>
        <div>{{ item.desc }}</div>
        <div>{{ item.price }}</div>
        <a class="btn btn-primary" href={{ url_for("menu_item.update", restaurant_id=restaurant.id, menu_item_id=item.id) }}>Edit</a>
        <a class="btn btn-danger" href="{{ url_for("menu_item.delete", restaurant_id=restaurant.id, menu_item_id=item.id) }}">Delete</a>

    {% endfor %}


{% endblock %}