controllers/restaurant_cont.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from models.restaurants import Restaurant, db
from flask import session as login_session

# make a restaurant blueprint
restaurant = Blueprint('restaurant', __name__)


# index to display all restaurants
# only dispaly the CRUD version of the webpage if users are logged in
# otherwise we serve a read only version of the page
@restaurant.route('/restaurants/')
def index():
    restaurants = Restaurant.query.all()
    user_id = login_session.get('id')
    if user_id:
        return render_template("restaurant/index.html", restaurants=restaurants)
    else:
        return render_template("restaurant/logged_out_index.html", restaurants=restaurants)


# creates a new restaurant and serves the form to do so
# upon successful creation redirect to index, otherwise
# flash the error and re-render the form template
@restaurant.route("/restaurant/new/", methods=['GET', 'POST'])
def create():
    user_id = login_session.get('id')
    if user_id:
        if request.method == 'GET':
            return render_template("restaurant/form.html", restaurant='')
        elif request.method == 'POST':
            rest_name = request.form.get("restaurant_name")
            if rest_name:
                new_restaurant = Restaurant(name=rest_name, user_id=login_session.get('id'))
                db.session.add(new_restaurant)
                db.session.commit()
                return redirect(url_for("restaurant.index"))
            else:
                flash("Please enter a valid restaurant name")
                return render_template("restaurant/form.html", restaurant='')
        else:
            flash("Invalid Submission, please try again")
            return render_template("restaurant/form.html", restaurant='')
    else:
        flash("operation not allowed. Please log in to create a restaurant")
        return redirect(url_for('restaurant.index'))


# Updates the name of an existing restaurant
# if the restaurant cannot be found, we'll flash an error and re-render the form
@restaurant.route("/restaurant/<int:restaurant_id>/edit/", methods=['GET', 'POST'])
def update(restaurant_id):
    user_id = login_session.get('id')
    current_restaurant = Restaurant.query.get(restaurant_id)
    if user_id:
        if current_restaurant:
            if request.method == "GET":
                return render_template("restaurant/form.html", restaurant=current_restaurant)
            elif request.method == "POST":
                name = request.form.get("restaurant_name")
                if name:
                    current_restaurant.name = name
                    db.session.add(current_restaurant)
                    db.session.commit()
                    flash("Restaurant has been updated to {}".format(current_restaurant.name))
                    return redirect(url_for('restaurant.index'))
            else:
                flash("Invalid Request, please try again")
                return render_template("restaurant/form.html", restaurant='')
        else:
            flash("The restaurant could not be found. Please try again")
            return render_template("restaurant/form.html", restaurant='')
    else:
        flash("operation not allowed. Please log in to update a restaurant")
        return redirect(url_for('restaurant.index'))


# route to delete a restaurant
# only allow the delete if a user is logged in
@restaurant.route("/restaurant/<int:restaurant_id>/delete/", methods=['GET', 'POST'])
def delete(restaurant_id):
    current_restaurant = Restaurant.query.get(restaurant_id)
    user_id = login_session.get('id')
    if user_id:
        if current_restaurant:
            if request.method == "GET":
                return render_template("restaurant/delete.html", restaurant=current_restaurant)
            elif request.method == 'POST':
                db.session.delete(current_restaurant)
                db.session.commit()
                flash("Restaurant Deleted Successfully!")
                return redirect(url_for("restaurant.index"))
            else:
                flash("Invalid Request, please try again")
                return render_template("restaurant/delete.html", restaurant='')
        else:
            flash("Restaurant not found, please try again")
            return render_template("restaurant/delete.html", restaurant='')
    else:
        flash("operation not allowed please log in to delete a restaurant item")
        return redirect(url_for('restaurant.index'))


@restaurant.route("/restaurant/<int:restaurant_id>/menu")
def show_menu(restaurant_id):
    current_restaurant = Restaurant.query.get(restaurant_id)
    user_id = login_session.get('id')
    if current_restaurant:
        if user_id:
            return render_template("restaurant/menu.html", restaurant=current_restaurant)
        else:
            return render_template("restaurant/logged_out_menu.html", restaurant=current_restaurant)
    else:
        flash("Restaurant not found. Please try again")
        return render_template("restaurant/index.html", restaurant='')

templates/menu/delete.html
{% extends "layout.html" %}

{% block nav %}
    {% include 'heading.html' %}
{% endblock %}

{% block content %}

    <h3>Are you sure you want to delete {{ menu_item.name }} from {{ menu_item.restaurant.name }}?</h3>

    <form method="post">
        <button class="btn btn-danger" type="submit">Delete</button>
        <a class="btn btn-success" href="{{ url_for("restaurant.show_menu", restaurant_id=menu_item.restaurant.id) }}">Cancel</a>
    </form>

{% endblock %}

templates/menu/form.html
{% extends "layout.html" %}

{% block nav %}
    {% include 'heading.html' %}
{% endblock %}

{% block content %}

    <h3>Add an item to {{ restaurant.name }} menu</h3>
    <form method="post">
        <div class="form-group">
            <label>Item Name</label>
            <input type="text" name="name" class="form-control" value="{{ menu_item.name }}">
        </div>

        <div class="form-group">
            <label>Description</label>
            <textarea name="desc" class="form-control" rows="3">{{ menu_item.desc }}</textarea>
        </div>

        <div class="form-group">
            <label>Price</label>
            <input type="text" name="price" class="form-control" value="{{ menu_item.price }}">
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
            <a class="btn btn-success" href={{ url_for("restaurant.show_menu", restaurant_id=restaurant.id) }}>Cancel</a>
        </div>
    </form>

{% endblock %}